Repository hummingbot/hummingbot, pull requests merged in 2022-02, with the labels that each got.

#2442 Feat / Add AltMarkets.io Exchange
  README.md
  assets/altmarkets_logo1.png
  conf/__init__.py
  hummingbot/connector/connector_status.py
  hummingbot/connector/exchange/altmarkets/__init__.py
  hummingbot/connector/exchange/altmarkets/altmarkets_active_order_tracker.pxd
  hummingbot/connector/exchange/altmarkets/altmarkets_active_order_tracker.pyx
  hummingbot/connector/exchange/altmarkets/altmarkets_api_order_book_data_source.py
  hummingbot/connector/exchange/altmarkets/altmarkets_api_user_stream_data_source.py
  hummingbot/connector/exchange/altmarkets/altmarkets_auth.py
  hummingbot/connector/exchange/altmarkets/altmarkets_constants.py
  hummingbot/connector/exchange/altmarkets/altmarkets_exchange.py
  hummingbot/connector/exchange/altmarkets/altmarkets_http_utils.py
  hummingbot/connector/exchange/altmarkets/altmarkets_in_flight_order.py
  hummingbot/connector/exchange/altmarkets/altmarkets_order_book.py
  hummingbot/connector/exchange/altmarkets/altmarkets_order_book_message.py
  hummingbot/connector/exchange/altmarkets/altmarkets_order_book_tracker.py
  hummingbot/connector/exchange/altmarkets/altmarkets_order_book_tracker_entry.py
  hummingbot/connector/exchange/altmarkets/altmarkets_user_stream_tracker.py
  hummingbot/connector/exchange/altmarkets/altmarkets_utils.py
  hummingbot/connector/exchange/altmarkets/altmarkets_websocket.py
  hummingbot/templates/conf_global_TEMPLATE.yml
  test/connector/exchange/altmarkets/.gitignore
  test/connector/exchange/altmarkets/__init__.py
  test/connector/exchange/altmarkets/test_altmarkets_auth.py
  test/connector/exchange/altmarkets/test_altmarkets_exchange.py
  test/connector/exchange/altmarkets/test_altmarkets_order_book_tracker.py
  test/connector/exchange/altmarkets/test_altmarkets_user_stream_tracker.py
  test/hummingbot/connector/exchange/altmarkets/__init__.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_api_order_book_data_source.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_api_user_stream_data_source.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_auth.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_exchange.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_in_flight_order.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_order_book.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_order_book_message.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_order_book_tracker.py
  test/hummingbot/connector/exchange/altmarkets/test_altmarkets_websocket.py
Labels: new connector

#5099 (fix) Fixes PNL issue on `history` command.
  hummingbot/client/performance.py
  hummingbot/connector/markets_recorder.py
  hummingbot/core/event/events.py
  hummingbot/model/trade_fill.py
  test/hummingbot/client/test_performance.py
  test/hummingbot/connector/test_markets_recorder.py
  test/hummingbot/core/data_type/test_in_flight_order.py
Labels: hotfix

#5110 hotfix / version 1.0.1
  hummingbot/VERSION
  hummingbot/client/performance.py
  hummingbot/connector/markets_recorder.py
  hummingbot/core/event/events.py
  hummingbot/model/trade_fill.py
  setup.py
  test/hummingbot/client/test_performance.py
  test/hummingbot/connector/test_markets_recorder.py
  test/hummingbot/core/data_type/test_in_flight_order.py
Labels: revert -> master, hotfix
