Repository hummingbot/hummingbot, pull requests merged in 2022-01, with the labels that each got.

#4974 gateway / sync changes from CoinAlpha feature branch
  .gitignore
  gateway/docs/swagger/avalanche-routes.yml
  gateway/docs/swagger/definitions.yml
  gateway/docs/swagger/eth-routes.yml
  gateway/docs/swagger/main-routes.yml
  gateway/docs/swagger/wallet-routes.yml
  gateway/manual-tests/curl.sh
  gateway/manual-tests/requests/add_ethereum_key.json
  gateway/manual-tests/requests/avalanche_nonce.json
  gateway/manual-tests/requests/eth_allowances.json
  gateway/manual-tests/requests/eth_approve.json
  gateway/manual-tests/requests/eth_approve_with_fees.json
  gateway/manual-tests/requests/eth_approve_with_nonce.json
  gateway/manual-tests/requests/eth_balances.json
  gateway/manual-tests/requests/eth_cancel.json
  gateway/manual-tests/requests/eth_nonce.json
  gateway/manual-tests/requests/eth_remove_allowance.json
  gateway/manual-tests/requests/eth_uniswap_trade.json
  gateway/manual-tests/requests/eth_uniswap_trade_with_fees.json
  gateway/package.json
  gateway/setup/create_certs.sh
  gateway/src/app.ts
  gateway/src/chains/avalanche/avalanche.validators.ts
  gateway/src/chains/ethereum/ethereum.controllers.ts
  gateway/src/chains/ethereum/ethereum.requests.ts
  gateway/src/chains/ethereum/ethereum.validators.ts
  gateway/src/chains/ethereum/uniswap/uniswap.controllers.ts
  gateway/src/chains/ethereum/uniswap/uniswap.requests.ts
  gateway/src/chains/ethereum/uniswap/uniswap.validators.ts
  gateway/src/https.ts
  gateway/src/services/config-manager-v2.ts
  gateway/src/services/ethereum-base.ts
  gateway/src/services/wallet/wallet.controllers.ts
  gateway/src/services/wallet/wallet.validators.ts
  gateway/test-scripts/README.md
  gateway/test-scripts/ethereum-base.test.ts
  gateway/test-scripts/ethereum.test.base.ts
  gateway/test-scripts/ethereum.test.ts
  gateway/test-scripts/uniswap.v2.test.ts
  gateway/test/app.test.ts
  gateway/test/chains/avalanche/avalanche.routes.test.ts
  gateway/test/chains/avalanche/pangolin/pangolin.routes.test.ts
  gateway/test/chains/ethereum/ethereum.controllers.test.ts
  gateway/test/chains/ethereum/ethereum.routes.test.ts
  gateway/test/chains/ethereum/ethereum.validators.test.ts
  gateway/test/chains/ethereum/uniswap/uniswap.routes.test.ts
  gateway/test/services/swagger-manager.test.ts
  gateway/test/services/wallet/wallet.routes.test.ts
  gateway/test/services/wallet/wallet.validators.test.ts
  gateway/yarn.lock
  hummingbot/client/command/gateway_command.py
  hummingbot/client/ui/completer.py
  hummingbot/client/ui/parser.py
  hummingbot/connector/gateway_base.py
  hummingbot/connector/gateway_in_flight_order.py
Labels: gateway

#4923 Fix/trade monitor freezing
  hummingbot/client/ui/interface_utils.py
  test/hummingbot/client/ui/test_interface_utils.py
Labels: 1 DP

#4988 Fix/Avellaneda MM - Randomly appearing RunTimeWarning on the log pane
  hummingbot/strategy/__utils__/trailing_indicators/trading_intensity.pyx
Labels: 1 DP

#4989 Fix/Avellaneda MM - Order refresh tolerance parameter not working
  hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
  test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making.py
Labels: 1 DP

#4993 Fix/Avellaneda - Verify the eta parameter
  hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
Labels: 1 DP

#4978 refactor/ Deprecate `MarketBase` module
  documentation/docs/developers/strategies/architecture.md
  documentation/docs/developers/strategies/perform-trade.md
  hummingbot/market/__init__.py
  hummingbot/market/deposit_info.pxd
  hummingbot/market/deposit_info.pyx
  hummingbot/market/eterbase/__init__.py
  hummingbot/market/market_base.pxd
  hummingbot/market/market_base.pyx
Labels: 1 DP

#4952 Refactor/Replace websockets library with aiohttp library - Bitmart
  hummingbot/connector/exchange/bitmart/bitmart_api_order_book_data_source.py
  hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py
  hummingbot/connector/exchange/bitmart/bitmart_auth.py
  hummingbot/connector/exchange/bitmart/bitmart_exchange.py
  hummingbot/connector/exchange/bitmart/bitmart_in_flight_order.py
  hummingbot/connector/exchange/bitmart/bitmart_order_book.py
  hummingbot/connector/exchange/bitmart/bitmart_order_book_message.py
  hummingbot/connector/exchange/bitmart/bitmart_order_book_tracker.py
  hummingbot/connector/exchange/bitmart/bitmart_user_stream_tracker.py
  hummingbot/connector/exchange/bitmart/bitmart_utils.py
  hummingbot/core/web_assistant/connections/ws_connection.py
  hummingbot/core/web_assistant/ws_assistant.py
  test/hummingbot/connector/exchange/bitmart/test_bitmart_api_order_book_data_source.py
  test/hummingbot/connector/exchange/bitmart/test_bitmart_api_user_stream_data_source.py
  test/hummingbot/connector/exchange/bitmart/test_bitmart_user_stream_tracker.py
  test/hummingbot/core/web_assistant/connections/test_ws_connection.py
Labels: 1 DP

#4998 Fix/command option help
  .coveragerc
  hummingbot/client/hummingbot_application.py
  hummingbot/client/ui/parser.py
Labels: 1 DP

#4999 Refactor/ascend ex exchange addresses
  hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py
  hummingbot/connector/exchange/ascend_ex/ascend_ex_api_user_stream_data_source.py
  hummingbot/connector/exchange/ascend_ex/ascend_ex_auth.py
  hummingbot/connector/exchange/ascend_ex/ascend_ex_constants.py
  hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py
  hummingbot/connector/exchange/ascend_ex/ascend_ex_utils.py
  test/hummingbot/connector/exchange/ascend_ex/test_ascend_ex_utils.py
Labels: 1 DP

#5004 fix/improve db session management
  hummingbot/client/command/config_command.py
  hummingbot/client/command/export_command.py
  hummingbot/client/command/history_command.py
  hummingbot/client/performance.py
  hummingbot/client/ui/interface_utils.py
  hummingbot/connector/exchange/binance/binance_order_book.pyx
  hummingbot/connector/exchange/bitfinex/bitfinex_order_book.pyx
  hummingbot/connector/exchange/blocktane/blocktane_order_book.pyx
  hummingbot/connector/exchange/coinbase_pro/coinbase_pro_order_book.pyx
  hummingbot/connector/exchange/huobi/huobi_order_book.pyx
  hummingbot/connector/exchange/kucoin/kucoin_order_book.pyx
  hummingbot/connector/exchange/loopring/loopring_order_book.pyx
  hummingbot/connector/exchange/okex/okex_order_book.pyx
  hummingbot/connector/markets_recorder.py
  hummingbot/core/data_type/order_book.pyx
  hummingbot/model/__init__.py
  hummingbot/model/db_migration/migrator.py
  hummingbot/model/db_migration/transformations.py
  hummingbot/model/decimal_type_decorator.py
  hummingbot/model/inventory_cost.py
  hummingbot/model/order.py
  hummingbot/model/sql_connection_manager.py
  hummingbot/model/trade_fill.py
  hummingbot/strategy/pure_market_making/inventory_cost_price_delegate.py
  setup/environment-linux-aarch64.yml
  setup/environment-linux.yml
  setup/environment-win64.yml
  setup/environment.yml
  test/hummingbot/client/command/test_history_command.py
  test/hummingbot/connector/test_markets_recorder.py
  test/hummingbot/model/__init__.py
  test/hummingbot/model/db_migration/__init__.py
  test/hummingbot/model/db_migration/test_transformations.py
  test/hummingbot/strategy/pure_market_making/test_inventory_cost_price_delegate.py
Labels: 1 DP

#5006 gateway / sync changes from CoinAlpha feature branch
  .github/CODEOWNERS
  .github/workflows/workflow.yml
  .pre-commit-config.yaml
  gateway/conf/samples/root.yml
  gateway/jest.config.js
  gateway/src/app.ts
  gateway/src/chains/ethereum/ethereum.ts
  gateway/src/services/logger.ts
  gateway/src/services/schema/server-schema.json
  gateway/src/services/telemetry-transport.ts
  gateway/test/services/logger.test.ts
Labels: gateway

#5008 refactor / binance perpetual connector
  hummingbot/connector/client_order_tracker.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_auth.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_in_flight_order.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_order_book.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_order_book_tracker.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_user_stream_data_source.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_user_stream_tracker.py
  hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py
  hummingbot/connector/derivative/binance_perpetual/constants.py
  hummingbot/core/data_type/in_flight_order.py
  hummingbot/core/event/events.py
  test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_api_order_book_data_source.py
  test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_auth.py
  test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_derivative.py
  test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_user_stream_data_source.py
  test/hummingbot/connector/derivative/binance_perpetual/test_binance_perpetual_utils.py
  test/hummingbot/connector/test_client_order_tracker.py
Labels: 1 DP

#5023 fix/binance paper trade exchange name error
  hummingbot/connector/exchange/binance/binance_order_book_tracker.py
  test/hummingbot/connector/exchange/binance/test_binance_order_book_tracker.py
Labels: staging

#5020 fix/ `config` command accepting spaces in values
  hummingbot/client/hummingbot_application.py
Labels: staging

#5031 (fix) Removed unnecessary columns from the table
  hummingbot/model/trade_fill.py
Labels: staging

#5033 Fix/Avellaneda orders not cancelled
  hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
  hummingbot/strategy/conditional_execution_state.py
  hummingbot/strategy/twap/twap.py
  test/hummingbot/strategy/test_conditional_execution_state.py
Labels: staging

#5028 Fix/Avellaneda MM - fix reserved price calculation for the infinite time horizon
  hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
  test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making.py
Labels: staging

#5046 fix/ Docker build error libffi.so.6 not found
  Dockerfile
Labels: staging
